server:
  port: 8201

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.46.82.134:3306/shequ-acl?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: 120.46.82.134
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 8   # 最大连接数
        max-wait: -1    # 最大等待时间（毫秒），-1 表示无限等待
        max-idle: 8     # 最大空闲连接数
        min-idle: 0     # 最小空闲连接数